### ISSUE TITLE
Add https://coffeespace.org.uk/tools/colour.htm

### ISSUE THREAD

**Issue by danielbarry** [bradleytaunt/1kb.club#10]
Shortens colour names/values into the format `#XXX`. For example, `magenta` -> `#f0f`, `rgb(255,67,92)` -> `#f45`, etc.

The idea was to implement something that could be useful for others.

**Comment by danielbarry** [comment]
Note I switched the directory to add other projects. Another is https://coffeespace.org.uk/tools/avatar.htm

**Comment by bradleytaunt** [comment]
Sorry, could you explain this issue / feature in more detail?

**Comment by danielbarry** [comment]
@bradleytaunt Sorry I only just saw this. The links are supposed to be a submission for the 1kB club.
